#! /bin/sh

echo "Deleting all autogenerated stuff..."

rm -f *.o *.so config.* Makefile configure
rm -f Makefile.in aclocal.m4 confdefs.h ltconfig ltmain.sh aclocal*
rm -f install-sh mkinstalldirs missing depcomp
rm -f m4/Makefile m4/Makefile.in
rm -rf .libs .deps src/.libs src/.deps
rm -f src/*.o src/*.[ls][ao] *.[ls][ao]
rm -f src/Makefile.in src/Makefile libtool
rm -rf autom4te.cache stamp-* compile libacm-*

rm -rf src/.libs src/.deps src/*.lo src/*.la src/Makefile src/Makefile.in
rm -rf plugins/.libs plugins/.deps plugins/*.lo plugins/*.la
rm -f plugins/Makefile plugins/Makefile.in src/acmtool

